version: 2.1
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build Android APK
           paths:
           - android
          command: gradlew bundleRelease
      - run:
          name: Build iOS Archive
          command: |
            yarn ios:build
workflows:
  version: 2
  build-deploy:
    jobs:
      - build